version: '3.8'

services:
 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
 notes:
  build:
   context: .
  ports:
   - 8080:8080
   - 9229:9229
  environment:
   - SERVER_PORT=8080
   - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/elm
  volumes:
   - ./:/code
  command: npm run check

volumes:
 mongodb:
 mongodb_config: